name: mc-storm-strike
author: btror
description: StormCommand Storm Plugin
version: '${project.version}'
main: mclightningstrike.mclightningstrike.McLightningStrike
api-version: 1.13
commands:
  strike:
    description: calls storm strike command
    usage: /strike